version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mi-mongo'
    environment:
      MONGO_INITDB_DATABASE: bank
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"

  users-service:
    build: .
    image: users-service
    container_name: users-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      USER_ID: prueba-tecnica
      API_KEY: 2uJ24U2P7wEC6gynjJhKpz16QT0i1ALwTwZWTRcOXRY4eaGc