micronaut:
  application:
    name: usersService
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

mongodb.uri: mongodb://${MONGO_HOST}:${MONGO_PORT}

neutrino:
  url: https://neutrinoapi.net
  userId: ${USER_ID}
  apiKey: ${API_KEY}